SPECK Implementation: /home/runner/work/SPECK_Cipher_Verilog/SPECK_Cipher_Verilog/reference_implementation_cxx/speck.cpp File Reference
speck.cpp File Reference
#include <cinttypes>
#include <cstdio>
#include <bitset>
#include <iostream>
Macros
#define PRINT_EACH_ROW 1
Reference implementation of of SPECK 64/128.
#define ROR(x, r) ((x >> r) | (x << (64 - r)))
#define ROL(x, r) ((x << r) | (x >> (64 - r)))
#define R(x, y, k) (x = ROR(x, 8), x += y, x ^= k, y = ROL(y, 3), y ^= x)
#define ROUNDS 32
Functions
void encrypt (uint64_t cipherText[2], uint64_t const plainText[2], uint64_t const K[2])
int main ()
void printCurrentState (int iteration, uint64_t p0, uint64_t p1, uint64_t k0, uint64_t k1)
Macro Definition Documentation
PRINT_EACH_ROW
#define PRINT_EACH_ROW 1
Reference implementation of of SPECK 64/128.
Copyright
Virginia Tech & University of Passau
Definition at line 11 of file speck.cpp.
R
#define R (x, y, k) (x = ROR(x, 8), x += y, x ^= k, y = ROL(y, 3), y ^= x)
Definition at line 18 of file speck.cpp.
ROL
#define ROL (x, r) ((x << r) | (x >> (64 - r)))
Definition at line 16 of file speck.cpp.
ROR
#define ROR (x, r) ((x >> r) | (x << (64 - r)))
Definition at line 14 of file speck.cpp.
ROUNDS
#define ROUNDS 32
Definition at line 20 of file speck.cpp.
Function Documentation
encrypt()
void encrypt (uint64_t cipherText[2], uint64_t const plainText[2], uint64_t const K[2])
Definition at line 44 of file speck.cpp.
References printCurrentState(), R, and ROUNDS.
Referenced by main().
main()
int main ()
Definition at line 24 of file speck.cpp.
References encrypt().
printCurrentState()
void printCurrentState (int iteration, uint64_t p0, uint64_t p1, uint64_t k0, uint64_t k1)
Definition at line 37 of file speck.cpp.
Referenced by encrypt().